version: '3.7'

services:
  SQLServer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: SQLServer
    restart: always
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=${SA_PASSWORD}
    ports: 
    - '1433:1433'
    volumes: 
      ## TODO: Look into how to mac the volumes static and as a named volume
      ## Windows
      - c:\Projects\Databases\Data:/var/opt/mssql/data
      - C:\Projects\Databases\logs:/var/opt/mssql/logs
      ## Mac (Case sensitive)
      ##- /Users/jguadagno/sql/data:/var/opt/mssql/data
      ##- /var/folders/sql/logs:/var/opt/mssql/logs
  postgresql:
    image: "postgres"
    container_name: "postgres"
    hostname: "postgres"
    restart: "no"
    environment:
      POSTGRES_PASSWORD: ${SA_PASSWORD}
    ports:
      - 5432:5432
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    container_name: "azurite"
    hostname: "azurite"
    restart: "no"
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:latest
    restart: "no"
    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
